name: Check

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches-ignore: [ "main" ]

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Deps
        run: |
          npm install

      - name: Run Lint
        run: npm run lint

      - name: Run TS Check
        run: npm run typecheck

      - name: Run Test
        run: npm run test
